---
name: Publish Package to npmjs

on:
  release:
    types: [published]
  push:
    branches:
      - 3.0

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          # Defaults to the user or organization that owns the workflow file
          scope: '@nolemonnomelon'
      - run: yarn
      - run: yarn publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
